UUIDTYPES = [('generic', '100', 'Catalog Object'),
             ('challenge_problem', '101', 'Challenge Problem'),
             ('experiment', '102', 'Experiment'),
             ('sample', '103', 'Sample'),
             ('measurement', '104', 'Measurement'),
             ('file', '105', 'File'),
             ('pipeline', '106', 'Pipeline'),
             ('pipelinejob', '107', 'PipelineJob'),
             ('pipelinejob_event', '108', 'PipelineJob Event'),
             ('reference', '109', 'Reference File'),
             ('product', '110', 'PipelineJob Product'),
             ('upload', '111', 'Uploaded File'),
             ('dashboard', '113', 'Redash Dashboard'),
             ('experiment_design', '114', 'Experiment Design')]
