---
debug: true
logs:
  level: INFO
catalogstore:
  uuid5_namespace: sd2e.org
  storage_system: data-sd2e-community
  base: ./tests/store
  store: uploads/
  root: uploads/
  batch: 1000
  collection: datafiles
  collections:
    files: datafiles
    samples: samples
    measurements: measurements
mongodb:
  #host: localhost
  host: data-catalog.sd2e.org
  port: 27020
  username: catalog
  password: ~
  database: catalog
storagesystems:
  data-sd2e-community:
    posix_path: ./store
linked_reactors:
  capture_fixity:
    id: gloqkNWaZLqjZ
    ignore_err: false
  ingest_samples_json:
    id: D0bvrrM4qLwgr
    options: ~
experiment_reference:
  schema_default_status: DRAFT
  google_sheets_dir: /
  google_sheets_id: 1FYOFBaUDIS-lBn0fr76pFFLBbMeD25b3
  slugify:
    stopwords:
      - Archive
      - CP
      - Experimental
      - Request
      - docx
      - doc
      - Template
    case: title
    separator: '-'
    case_insensitive: False
google_client:
  type: service_account
  project_id: sd2e-sheets-1534279057631
  private_key_id: ~
  private_key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCzGCxxoudKI73J
    UYdnjJZxnB/r6uuYDMAO/MHro0TfVEDooPjAPjoDJ6+QvxbptwW0t+UAyBdB4+nT
    K0cVnMX6Kpssg9rJxcgChm5xapT9NooqLuoSjPiTb1odG9SigIfqsacOBNDm+pFl
    czA98/R/P8PE9hEjpynQV5T7vTMNCNx8jdnu41gBdO30rngw8oaMSwSJwaIi9jyv
    F2GoylAO0Sq4C4oURYry1KQZIDrITAtu3C6QT2++2NOD8nR9k1LyEyGr7stU61Hv
    zNYCFOzcKrkPXS6V896izLmZ81MD4Zn+IqMF+UU4IBvHmHTiRLk0NiNCsYxsYQ9i
    STh9Dq3zAgMBAAECggEABmtOZIBPQ/QGAGpArTB3z/ilmEIiUZ/bXm4m0ThX5p1R
    ekUSxWk1kRliDJEc1CGwPar9tUp2svDlV6FMefTVj8LpLu5G8EZ7hcOlv8DvOCg1
    SY/G6gVNf5NVKoft1ik/NeVKNJFtn2nJvlYjm4Tb9Zemf6/GK335XLNW7rL4WnYw
    ejR1ve52LwkddfI6w5N8tFoKFYo5PMTHVpqpPj015oWqWyY9GDKXRarhPYwoUCmo
    Ing2hK2GvDWFzzyO7GWVSsOXQkQeW2A9E7noD0l619RTw/i4jAEWYGbj83p5iguU
    1qaWbJOHc0APpdLSiGfX+OnA01pYJeRKO9GPZEfkaQKBgQDhgOuLQag/dMAR+dAD
    rHXARhmR2mTZNHVKCkQuoIFyYRh4ghmqnI2JOfOBj7k73F08u4aJ0uWi6hnQ300h
    Ohz9KL0KCe8Ja/gp8Uhfzi9hixfcPPpE/P1m6MiY2I87JcLsymNtSod0blLK/Kjd
    EgQPkFyOsdEmhxKQlUGICXKQjwKBgQDLUInKw+CE0ve4celijnyGpVzicB54nMPZ
    +NnBQ/Um8ao2+L2kyZlU2QNBqL71u3Ba8oGsfVOhs+oOcIMWWOBotisKrfIs/GSO
    xMIrT4T4s5NJxZUY0SDt61sqofUlpto/ildzShubhRZYUzjKW0X2LBum+O+1wROh
    jfOdEe42XQKBgDwD9axQQxjwV5XxKH1xzrznazK4LxLntTeJV/AY45qvYLXh2jbg
    B4M4GyimOaRG18GsHvhbWqZrK4e9hmeLcd+mkfkz/5xAUgHHp31oAJAzVpxU1j66
    Hi7fUVPsfuI9AI3Ip4GUzkwceIhxifecLdx+jUOk64cXd8dnEdPEv+rdAoGBAMDt
    muOi/fFsdA89YNbaGMZ4MmzZMcEIGT1Ey/V+NCqRVhE19ldhyjNefp2WsCZkiFh1
    GKIChxLBtA+hqnLRQZl7i9pld5JCqnVjtlD881RAqzps2G+lOxcpp+gLqaHh8+Yp
    s5Q+NXZdUvfbeN9kvz27Wz4VqPoSzjsWhZ59vkstAoGAdfhQ0g93rgJeaQ6H1eKV
    qJd3FG+6mCgikuqtdc5V8ilqg5BepOUGgPIbu2Jd7Qhp8GWCVpYoaQN7qLQmruNj
    p8A6OWceDa0GbkeorbUlQlyPmrAHy5qP2wvGu+jyGw1D9KjTUyGkM++kYBymaBh+
    2Ib37DwywVLb0AuuE2MnBFk=
    -----END PRIVATE KEY-----
  client_email: ~
  client_id: ~
  auth_uri: https://accounts.google.com/o/oauth2/auth
  token_uri: https://oauth2.googleapis.com/token
  auth_provider_x509_cert_url: https://www.googleapis.com/oauth2/v1/certs
  client_x509_cert_url: ~
pipelines:
  pipeline_uuid: 6e6a46f5-fed7-57fa-89e7-527ce8c13c91
  updates_nonce: ~
  authn: ~
  pipeline_manager_id: G1p783PxpalBB
  job_manager_id: G56vjoAVzGkkq
  api_server: https://api.sd2e.org
  database: catalog
